{
  "formatVersion": "1.1",
  "component": {
    "group": "com.silvertip.meta",
    "module": "clickPlugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "clickPlugin-1.0.1.jar",
          "url": "clickPlugin-1.0.1.jar",
          "size": 20351,
          "sha512": "237799afac5bde3c807e8a3c30d30ce9a9f1d972dd57c44a393f2370056379e9d2e096b2393c43318b56b37163697eee706bd8ceb70ec130127d7958270d5f54",
          "sha256": "9a4787ffebf650e7dfddfc656d49085de452fd42da81086df69ad765b7ade2f8",
          "sha1": "163c8691f982827be2d0c2a01ab3a79309c02c03",
          "md5": "be184f95bd8d16aa13b120ad8507aacc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "clickPlugin-1.0.1.jar",
          "url": "clickPlugin-1.0.1.jar",
          "size": 20351,
          "sha512": "237799afac5bde3c807e8a3c30d30ce9a9f1d972dd57c44a393f2370056379e9d2e096b2393c43318b56b37163697eee706bd8ceb70ec130127d7958270d5f54",
          "sha256": "9a4787ffebf650e7dfddfc656d49085de452fd42da81086df69ad765b7ade2f8",
          "sha1": "163c8691f982827be2d0c2a01ab3a79309c02c03",
          "md5": "be184f95bd8d16aa13b120ad8507aacc"
        }
      ]
    }
  ]
}
